// Generated by steam-bridge-input. Do not edit by hand.
// Source: steam_input_manifest.vdf
import { defineSteamInput } from "steam-bridge";

export const steamInputDefinition = defineSteamInput({
  actionSets: {
    "gameplay": "gameplay",
    "menu": "menu"
  },
  actionLayers: {
    "inventory": "inventory"
  },
  digital: {
    "accept": "accept",
    "cancel": "cancel",
    "jump": "jump",
    "pause": "pause"
  },
  analog: {
    "move": "move"
  }
} as const);

export type SteamInputDefinition = typeof steamInputDefinition;
